name: flutter_asset_generator
email: cjl_spy@163.com
homepage: https://github.com/CaiJingLong/flutter_resource_generator
version: 1.0.1
description: Automatically generate a resource file by scanning pubspec.yaml to correspond to the flutter's asset, imitation R file short name.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.1
  dart_style: ^2.0.2
  glob: ^2.0.1
  io: ^1.0.3
  path: ^1.8.0
  yaml: ^3.1.0

executables:
  fgen: resource_generator
